### ISSUE TITLE
Custom Github Action

### ISSUE THREAD

**Issue by abanna** [nerds-run/odious-ado#18]
```yaml
action: odious_ado@v1
with:
  mappings:
        thing: thing2
         thing1: thing3
  title: Monthly issue metrics report
  token: ${{ secrets.GITHUB_TOKEN }}
   content-filepath: ./issue_metrics.md
   assignees: <YOUR_GITHUB_HANDLE_HERE>
```
